# Lambdas

In [5]:
first_last = lambda x,y : f"{y}, {x}"
print(first_last("hello","world"))

world, hello


In [10]:
print(list(map(lambda x: x*x, [1,2,3,4,5])))

[1, 4, 9, 16, 25]


In [9]:
squares = lambda x : [i**2 for i in x]
print(squares([1,2,3,4,5]))

[1, 4, 9, 16, 25]


# NumPy

In [4]:
import numpy as np

array_1_10 = np.arange(1,10)

# using reshape to convert 1D array to 3x3 matrix
array_3_3 = array_1_10.reshape(3,3)
print(array_3_3)

# transpose of a matrix
array_3_3_T = array_3_3.T
print(array_3_3_T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
ndim_array = np.array([1,2,3,4,5], ndmin=2)
print(ndim_array)

[[[[[1 2 3 4 5]]]]]


In [7]:
np.tile(array_3_3, 2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [8]:
array_3_3[1,1], array_3_3[1],[1]

(5, array([4, 5, 6]), [1])