In [69]:
import numpy as np
import pandas as pd
### Submitted on EConestoga Assignment Dropbox

In [70]:
def no_zeros(arrayInput):
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: [1,2,3,4,5,6,0] Sample Output: False
    return  np.all(arrayInput != 0)

print(no_zeros(np.array([1,2,3,4,5,6,1])))
print(no_zeros(np.array([1,2,3,4,5,6,0])))

True
False


In [71]:
def linearly_distributed(n, min, max):
    ## TODO: This function should return a numpy array of 
    ## length n with equally spaced elements from 
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods
    ## Sample input: (0,100,4) sample output [0,33,66, 99]
    return np.linspace(min, max, num=n)
    
 # Example usage:
print(linearly_distributed(4,0,100))


[  0.          33.33333333  66.66666667 100.        ]


In [72]:
def two_dimensions(n):
    ## TODO: This function should create a 2d Array of shape n*n
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],
    ##                [1,0,1],
    ##                [1,1,1]]
    arr = np.zeros((n, n))
    arr[0, :] = 1 # is a way of slicing the array. 
    # 0 specifies the first row of the array. 
    # : means "all columns" in the selected row.
    arr[-1, :] = 1
    arr[:, 0] = 1
    arr[:, -1] = 1
    return arr

print(two_dimensions(3))
    

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [73]:
def create_array(n,min,max):
    ## TODO: This function should return a numpy array of 
    ## length n with equally random elements from 
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods
    ## Sample Input (10,0,10) sample output(0,2,2,3,1,5,9,7,8,3)
    
    return np.random.randint(min, max, size=n)

print(create_array(10,0,10))

[7 4 7 3 5 3 0 2 3 3]


In [74]:
def random_generation(n,min,max):
    ## TODO: Write a function that takes as an input
    ## Dimension of 2d Array n, min and max
    ## Generate an n*n array with random numbers between
    ## min and max inclusive
    ## Such that no element is duplicated
    ## return numpy array
    ## Implement this function using ONLY numpy methods
    arr = np.arange(min, max+1)
    np.random.shuffle(arr)
    return arr[:n*n].reshape(n, n)

print(random_generation(3,0,8))

[[7 4 0]
 [8 5 1]
 [6 3 2]]


In [75]:
def filtered_dataframe(csv_path):
    ## TODO: Write a function that takes as an input csv file path
    ## of the pandas_tutorial_read
    ## Filter the dataframe on articles from county_2
    ## Where topic is Asia 
    ## print: date_time, user_id and event
    ## Note: (Column names are in the slides)
    
    df = pd.read_csv(csv_path, delimiter=';')
    df.columns = ['date_time', 'event', 'country', 'user_id', 'role', 'topic']
    df = df[(df['country'] == 'country_2') & (df['topic'] == 'Asia')]
    print(df[['date_time', 'user_id', 'event']])
    

filtered_dataframe('pandas_tutorial_read.csv')
    

                date_time     user_id event
16    2018-01-01 00:13:06  2458151278  read
18    2018-01-01 00:14:53  2458151280  read
19    2018-01-01 00:15:44  2458151281  read
22    2018-01-01 00:17:31  2458151284  read
27    2018-01-01 00:23:16  2458151289  read
...                   ...         ...   ...
1774  2018-01-01 23:47:19  2458153036  read
1777  2018-01-01 23:51:17  2458153039  read
1780  2018-01-01 23:51:52  2458153042  read
1781  2018-01-01 23:53:03  2458153043  read
1786  2018-01-01 23:54:45  2458153048  read

[179 rows x 3 columns]
